### ISSUE TITLE
FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by Pronner** [ashraf789/Cake-VPN#127]
I've received multiple crash reports after putting this up on Google Play (after I modified the code and the design, and no it is not called "CakeVPN")

This has been tested on the `Google Pixel 6` by a Google Tester/Employee I guess?

Info:
Memory: 8,192 MB
OpenGL ES Version: 3.2
ABI: arm64-v8a
Android Version: 
Android 12 (SDK 31)
Screen Size: 1080 x 2400

Error:
```logcat
FATAL EXCEPTION: main
Process: com.pronner.ragtagvpn, PID: 19954
java.lang.RuntimeException: Unable to start service de.blinkt.openvpn.core.OpenVPNService@49c7caa with Intent { cmp=com.pronner.ragtagvpn/de.blinkt.openvpn.core.OpenVPNService (has extras) }: java.lang.IllegalArgumentException: com.pronner.ragtagvpn: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4657)
	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: com.pronner.ragtagvpn: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
	at de.blinkt.openvpn.core.OpenVPNService.getGraphPendingIntent(OpenVPNService.java:491)
	at de.blinkt.openvpn.core.OpenVPNService.showNotification(OpenVPNService.java:334)
	at de.blinkt.openvpn.core.OpenVPNService.onStartCommand(OpenVPNService.java:586)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
	... 9 more
```
Not sure what to do, as this has worked on my device.

**Comment by cherimo** [comment]
Same here!

**Comment by assilMekki** [comment]
Hello, did you guys find any solutions for this please? Thank you
